### ISSUE TITLE
Rewrite in Rust

### ISSUE THREAD

**Issue by Jake-Shadle** [EmbarkStudios/nfd2#11]
This crate basically provides a thin wrapper around the nativefiledialog C library, which itself is just a small abstraction on top of the OS dialogs. While nativefiledialog is small and easy to build, there's really no good reason why we can't go directly to the OS dialogs inside Rust without needing to have a submodule/wrapper for a C library.

**Comment by repi** [comment]
I have a crate that is a start for that and that does it natively for Windows and that works really well, but we would need to implement Linux and MacOS support, which is a bit messy.

**Comment by PolyMeilex** [comment]
I had working Linux and Windows crate laying somewhere on my hard drive, ~~but I abandoned it because I have no way to test macOS implementation~~
It's totally doable, and it does not require that much work, so let me know if you decide to work on project like this.

**Comment by adamnemecek** [comment]
@PolyMeilex @repi why don't you guys post these online?

**Comment by PolyMeilex** [comment]
Sure, for anyone interested here is my project (for win,gtk,macos and wasm) https://github.com/PolyMeilex/rfd
It also supports async/await syntax, which helps a lot with macOS dialogs, as those can't be multi threaded.
Feel free to give it a try.

**Comment by repi** [comment]
hi @PolyMeilex, @emilk in our team have switch us at Embark to use your new crate now, awesome work on it! 

We'll test it for a bit now across platforms and see if we run into any issues. but if it works well I think we'll close and archive this crate and repro and redirect to `rfd`!

**Comment by repi** [comment]
@PolyMeilex would be cool to collaborate on some crates and chat, ping us on [our Discord](https://discord.gg/8TW9nfF) or drop us a mail on `opensource@embark-studios.com` if you are interested :)

**Comment by PolyMeilex** [comment]
Hi! If you encounter any problems, or missing features in `rfd` fell free to open issues, I'm quite open to the scope of the crate, so as long as it's dialog related (not necessarily file dialogs) I will most likely accept it.

**Comment by parasyte** [comment]
I'll add that I used `rfd`'s async impl with `pollster` in one of my projects last month and it was a super smooth experience. Just a positive experience report. I haven't noticed anything missing or any bugs to address.

**Comment by repi** [comment]
We've transitioned fully over to `rfd` now and haven't had any problems since on Windows, Mac or Linux. Thanks @PolyMeilex !

So think we can consider this issue closed. And we can close/deprecate/archive this crate and repo. Filed #22 for that.

**Comment by PolyMeilex** [comment]
Great to hear that
