### ISSUE TITLE
Response should return OsString

### ISSUE THREAD

**Issue by snakehand** [EmbarkStudios/nfd2#4]
**I don't think it is possible to return a file selection if the file name is not utf8**
The Response returns a String, which must be valid utf8. The same constraint does not apply to files on the file system, consequently it is not possible to get a usable representation of the file name to such a file.

**Alternative methods should be added with a new Response type**
For instance a "OsResponse" enum with Okay(OsString) could be returned from the new method.

**Comment by Jake-Shadle** [comment]
Ahh, I didn't notice that when I forked the crate, I think I'll just make a breaking change to only return PathBufs, with convenience methods to convert to strings if possible.
